### PR TITLE
adds several fun things and loadout items

### PR DESCRIPTION
**Pull request by Jamini**
added a less-suspicious turtleneck
added laserpointers
added balls
added a number of objects to loadout lists
added ability to have icon path transforms for the mask slot
bandanas (the mask ones) now fit and display on the face and head. (Helmet bananas do not do this currently)

## Why It's Good For The Game

Let it snow, let it snow, let it snow!
Because I want to be a pretty snowflake too, damn it!

## Changelog
```changelog
add: A less-suspicious turtleneck
add: Laserpointers
add: tennis balls
tweak: added a number of objects to loadout lists
tweak: added ability to have icon path transforms for the mask slot
tweak: bananas (the mask ones) now fit and display on the face and head. (Helmet bananas do not do this currently!)
```

### CODE REVIEW

**Comment by Jamini** [comment]
image

Bolls

**Comment by Jamini** [comment]
Laserpointer icons were taken from skyrats/cit

image

**Comment by Jamini** [comment]
Travis didn't like an expression. Modified it a bit. Nothing major.

I've got some ideas for mob species transforms after this as well. Deffo not going in here, but I might take a crack at it soon thanks to insights from this.

**Comment by Jamini** [comment]
Helmet pathed bananas do not and have never had the code that allows you to wear them on both the mask and face. They only are availible via loadout and pirate corpse spawners now anyway. Fixed the loadout option to just use the mask version. The icon should update right away anyway on spawn while worn.

**Review by ShadzFen — APPROVED** [review]
Lots of fun new things! Everything looks good from here, and it's all tested and working. Probably as modular as it's gonna get.

**Pull request merged**
