### PR TITLE
Minor Sprite Fixes

### PR DESCRIPTION
**Pull request by Jamini**
Fixed asteroid turfs for minerals
Adjusted Tajaran icon to avoid bignose syndrome

## About The Pull Request

Fixed iconstates. Minor tweak to tajaran sprite

## Why It's Good For The Game

Fixes and stuff

## Changelog
```changelog
fix: Fixed asteroid turfs. Again.
```

### CODE REVIEW

**Review by Michiyamenotehifunana — APPROVED** [review]
Simple renaming of sprites and minor modifications, checks out.

**Review by ShadzFen — CHANGES_REQUESTED** [review]
Sort out the modified sprite issues that could potentially collapse the code.

**Comment by Jamini** [comment]
Updated as requested!

**Review by ShadzFen — APPROVED** [review]
Modularized as requested. All good!

**Pull request merged**
