### PR TITLE
marshals are now freelance bounty hunters

### PR DESCRIPTION
**Pull request by bearrrrrrrr**
## About The Pull Request

Reflavors Aegis Marshal to be a freelance bounty hunter.

## Why It's Good For The Game

Marshals can, at best, just be an extra Aegis officer. At worst, they can be validhunting tools.

## Changelog
```changelog
tweak: Aegis Marshal is now a bounty hunter.
```

### CODE REVIEW

**Review by ShadzFen — CHANGES_REQUESTED** [review]
Simple name and description changes. All good here, but it would be useful if you could put a **//Syzygy Edit.** in front of the edited names and description since it's not modular.

**Comment by bearrrrrrrr** [comment]
done! also, vote was already done @Torque4607

**Review by ShadzFen — APPROVED** [review]
Simple name and description changes, marked properly since it's not modular. All good here.

**Review by Michiyamenotehifunana — APPROVED** [review]
Looks about right. Perfectly in line with community votes as well.

**Pull request merged**
