### PR TITLE
Command Armoury Buff

### PR DESCRIPTION
**Pull request by Crosarius**
## About The Pull Request
This PR adds two NanoTrasen PP "Brigador" pistols to the Command Armory, and makes modular changes to the Brigador to give it a stun firing mode (using the existing plasma stun projectile which so far only the Martyr uses.) 

image
image

## Why It's Good For The Game
I'd like for there to be an energy counterpart to the existing Avasarala to add a little variety. Also, full disclosure of personal conflict of interest: I play a Command character with weak baby wrists who ICly has difficulty with the Avasarala.

## Changelog
```changelog
add: Adds two NanoTrasen PP "Brigador" to the Command Armory.
tweak: Gives the Brigador a stun firemode.
tweak: Makes the Command Armory slightly bigger.
```

### CODE REVIEW

**Review by Michiyamenotehifunana — APPROVED** [review]
Looks good, decisions on actually wanting it in the bridge armory not withstanding.

**Comment by Crosarius** [comment]
Don't merge this yet. With some further testing I realized that the icon for the brigador doesn't change when you swap the cell out. And that's because they literally didn't code it in. I'm coding it now.

**Comment by Crosarius** [comment]
Actually nevermind. This is ready for merge. The whole cell sprite thing is a superfluous feature that will require a lot of effort to implement for like 2 pixels of difference per power cell. I might get around to doing this in another PR in the future.

**Comment by Crosarius** [comment]
image

**Pull request merged**
